message(STATUS "========================================================")
message(STATUS "114514 THIS IS START OF arm-windows-static.cmake 1919810")
set(BTXH_SKU Enterprise)
set(VCPKG_TARGET_ARCHITECTURE arm)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_PLATFORM_TOOLSET v143)
set(VCPKG_CMAKE_SYSTEM_NAME Windows)
set(VCPKG_CMAKE_SYSTEM_VERSION 10.0.22621.0)
set(VCPKG_TARGET_ARCHITECTURE arm)
set(CMAKE_SYSTEM_VERSION 10.0.22621.0)
set(CMAKE_C_COMPILER "C:/Program Files (x86)/Microsoft Visual Studio/2022/${BTXH_SKU}/VC/Tools/MSVC/$ENV{VCToolsVersion}/bin/Hostx64/arm/cl.exe")
set(CMAKE_CXX_COMPILER "C:/Program Files (x86)/Microsoft Visual Studio/2022/${BTXH_SKU}/VC/Tools/MSVC/$ENV{VCToolsVersion}/bin/Hostx64/arm/cl.exe")
set(CMAKE_RC_COMPILER "C:/Program Files (x86)/Windows Kits/10/bin/10.0.22621.0/x64/rc.exe")
message(STATUS "VCINSTALLDIR == $ENV{VCINSTALLDIR}")
set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "${CMAKE_CURRENT_LIST_DIR}\\toolchain-arm.cmake")
message(STATUS "114514 THIS IS END OF arm-windows-static.cmake 1919810")
message(STATUS "======================================================")
