message(STATUS "===================================================")
message(STATUS "114514 THIS IS START OF toolchain-arm.cmake 1919810")
# THIS IS　triplets\\community\\toolchain-arm.cmake
set(BTXH_SKU Enterprise)
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR ARM)
message(STATUS "VCINSTALLDIR == $ENV{VCINSTALLDIR}")
message(STATUS "BTXH_SKU == ${BTXH_SKU}")
set(COMPILER_DIR "$ENV{VCToolsInstallDir}bin\\Hostx64\\arm")
set(CMAKE_SYSTEM_VERSION 10.0.22621.0)
set(VCPKG_CMAKE_SYSTEM_VERSION 10.0.22621.0) 
set(CMAKE_C_COMPILER "C:/Program Files (x86)/Microsoft Visual Studio/2022/${BTXH_SKU}/VC/Tools/MSVC/$ENV{VCToolsVersion}/bin/Hostx64/arm/cl.exe")
set(CMAKE_CXX_COMPILER "C:/Program Files (x86)/Microsoft Visual Studio/2022/${BTXH_SKU}/VC/Tools/MSVC/$ENV{VCToolsVersion}/bin/Hostx64/arm/cl.exe")
set(CMAKE_RC_COMPILER "C:/Program Files (x86)/Windows Kits/10/bin/10.0.22621.0/x64/rc.exe")
message(STATUS "Using ARM toolchain: ${CMAKE_C_COMPILER}")
message(STATUS "114514 THIS IS END OF toolchain-arm.cmake 1919810")
message(STATUS "=================================================")