message(STATUS "===================================================")
message(STATUS "114514 THIS IS START OF toolchain-arm.cmake 1919810")
# THIS IS　triplets\\community\\toolchain-arm.cmake
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR ARM)
message(STATUS "VCINSTALLDIR == $ENV{VCINSTALLDIR}")
set(COMPILER_DIR "$ENV{VCINSTALLDIR}\\bin\\Hostx64\\arm")
set(CMAKE_C_COMPILER "${COMPILER_DIR}\\cl.exe")
set(CMAKE_CXX_COMPILER "${COMPILER_DIR}\\cl.exe")
set(CMAKE_RC_COMPILER "$ENV{WindowsSdkDir}\\bin\\$ENV{WindowsSDKVersion}x64\\rc.exe")
set(CMAKE_SYSTEM_VERSION 10.0.22621.0)
set(VCPKG_CMAKE_SYSTEM_VERSION 10.0.22621.0) 
set(CMAKE_C_COMPILER "$ENV{VCINSTALLDIR}\\bin\\Hostx64\\arm\\cl.exe")
set(CMAKE_CXX_COMPILER "$ENV{VCINSTALLDIR}\\bin\\Hostx64\\arm\\cl.exe")
set(CMAKE_RC_COMPILER "$ENV{WindowsSdkDir}\\bin\\$ENV{WindowsSDKVersion}x64\\rc.exe")
message(STATUS "Using ARM toolchain: ${CMAKE_C_COMPILER}")
message(STATUS "114514 THIS IS END OF toolchain-arm.cmake 1919810")
message(STATUS "=================================================")