FROM debian:bullseye
MAINTAINER devseed

RUN  dpkg --add-architecture i386 && apt-get -y update \
    && apt-get -y install make cmake tar git wget curl \
    && apt-get -y install build-essential gcc-multilib g++-multilib \
    && apt-get -y install libx11-dev libxext-dev libasound2-dev \
    && apt-get -y install libgl1-mesa-dev mesa-utils \ 
    && apt-get -y install libx11-dev:i386 libxext-dev:i386 libasound2-dev:i386 \
    && apt-get -y install libgl1-mesa-dev:i386 mesa-utils:i386